# Generated by Django 6.0 on 2026-01-05 13:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nominated', models.BooleanField(default=False, verbose_name='يرشح للمقابلة/المرحلة التالية')),
                ('reason', models.CharField(blank=True, default='', max_length=250, verbose_name='سبب عدم الترشيح (إن وجد)')),
                ('final_score_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة النهائية (محسوبة)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
            ],
            options={
                'verbose_name': 'قرار نهائي',
                'verbose_name_plural': 'القرارات النهائية',
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='start_date',
        ),
        migrations.AddField(
            model_name='candidate',
            name='admin_exp',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='سبق العمل في الإدارة المدرسية'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='applied_position',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الوظيفة المتقدم عليها'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assigned_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to='candidates.committee', verbose_name='اللجنة المعيّنة'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_work',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='العمل الحالي'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_url',
            field=models.URLField(blank=True, default='', verbose_name='رابط السيرة الذاتية'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='file_not_eligible',
            field=models.BooleanField(default=False, verbose_name='لا يرشح (ملف)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='file_not_eligible_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='سبب عدم الترشيح (ملف)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='opportunity_school',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مدرسة الفرصة'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='opportunity_sector',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='قطاع الفرصة'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start_date_hijri',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='تاريخ المباشرة (هجري)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_deputy',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات عمل وكيل'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_director',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات عمل مدير'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_reviews', to=settings.AUTH_USER_MODEL, verbose_name='مقيّم الملف (مشرف)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='درجة الملف (0-50)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file_scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تقييم الملف'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalizations', to=settings.AUTH_USER_MODEL, verbose_name='اعتماد رئيس اللجنة'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='اسم المتقدم'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='مقفل/معتمد نهائيًا'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='السجل المدني'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الرتبة الوظيفية'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مدرسة المتقدم'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='قطاع المتقدم'),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='درجة المقابلة (0-50)'),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('opportunity', 'name')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['opportunity', 'national_id'], name='candidates__opportu_c349e4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['opportunity', 'assigned_committee'], name='candidates__opportu_96a33a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['opportunity', 'is_finalized'], name='candidates__opportu_c90996_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewscore',
            index=models.Index(fields=['committee', 'candidate'], name='candidates__committ_49dfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewscore',
            index=models.Index(fields=['member'], name='candidates__member__f25b96_idx'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_decision', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_decisions', to='candidates.committee'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_decisions', to=settings.AUTH_USER_MODEL, verbose_name='رئيس اللجنة'),
        ),
        migrations.AlterUniqueTogether(
            name='finaldecision',
            unique_together={('committee', 'candidate')},
        ),
    ]
