# Generated by Django 6.0 on 2026-01-05 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_finaldecision_remove_candidate_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=20, verbose_name='السجل المدني')),
                ('mobile_last4', models.CharField(max_length=4, verbose_name='آخر 4 من الجوال')),
                ('role', models.CharField(choices=[('supervisor', 'مشرف ملف'), ('member', 'عضو لجنة'), ('chair', 'رئيس لجنة'), ('admin', 'إدارة')], max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['opportunity', 'name'], name='candidates__opportu_d70e76_idx'),
        ),
        migrations.AddIndex(
            model_name='finaldecision',
            index=models.Index(fields=['committee', 'is_nominated'], name='candidates__committ_2fd549_idx'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='candidates.committee', verbose_name='اللجنة'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='candidates.opportunity', verbose_name='الفرصة'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['national_id', 'mobile_last4'], name='candidates__nationa_be9403_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['role'], name='candidates__role_d9f8ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['member', 'chair']), _negated=True), ('committee__isnull', False), _connector='OR'), name='memberprofile_committee_required_for_committee_roles'),
        ),
    ]
